# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'de-anony_tools.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DeAnony(object):
    def setupUi(self, DeAnony):
        DeAnony.setObjectName("DeAnony")
        DeAnony.resize(793, 683)
        self.centralwidget = QtWidgets.QWidget(DeAnony)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 751, 511))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 361, 481))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 250, 321, 237))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_aux = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        self.label_aux.setFont(font)
        self.label_aux.setObjectName("label_aux")
        self.verticalLayout_3.addWidget(self.label_aux)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textBrowser_aux = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_aux.setObjectName("textBrowser_aux")
        self.horizontalLayout_3.addWidget(self.textBrowser_aux)
        self.Browse_aux = QtWidgets.QPushButton(self.layoutWidget)
        self.Browse_aux.setObjectName("Browse_aux")
        self.horizontalLayout_3.addWidget(self.Browse_aux)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.tableView_aux = QtWidgets.QTableView(self.layoutWidget)
        self.tableView_aux.setObjectName("tableView_aux")
        self.verticalLayout_3.addWidget(self.tableView_aux)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 10, 321, 237))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_anony = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        self.label_anony.setFont(font)
        self.label_anony.setObjectName("label_anony")
        self.verticalLayout.addWidget(self.label_anony)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser_anony = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.textBrowser_anony.setObjectName("textBrowser_anony")
        self.horizontalLayout_2.addWidget(self.textBrowser_anony)
        self.Browse_anony = QtWidgets.QPushButton(self.layoutWidget1)
        self.Browse_anony.setObjectName("Browse_anony")
        self.horizontalLayout_2.addWidget(self.Browse_anony)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableView_anony = QtWidgets.QTableView(self.layoutWidget1)
        self.tableView_anony.setObjectName("tableView_anony")
        self.verticalLayout.addWidget(self.tableView_anony)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(380, 10, 361, 481))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(31, 161, 311, 311))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser_result = QtWidgets.QTextBrowser(self.layoutWidget2)
        self.textBrowser_result.setObjectName("textBrowser_result")
        self.verticalLayout_2.addWidget(self.textBrowser_result)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout_2.addWidget(self.pushButton_save)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 10, 311, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_result = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setObjectName("label_result")
        self.verticalLayout_5.addWidget(self.label_result)
        self.textBrowser_percentage = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser_percentage.setObjectName("textBrowser_percentage")
        self.verticalLayout_5.addWidget(self.textBrowser_percentage)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(370, 0, 20, 511))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.frame)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 550, 371, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(430, 550, 311, 67))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_weight = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_weight.setObjectName("pushButton_weight")
        self.horizontalLayout_4.addWidget(self.pushButton_weight)
        self.pushButton_run = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_run.setObjectName("pushButton_run")
        self.horizontalLayout_4.addWidget(self.pushButton_run)
        self.pushButton_totrun = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_totrun.setObjectName("pushButton_totrun")
        self.horizontalLayout_4.addWidget(self.pushButton_totrun)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.pushButton_quit = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.verticalLayout_4.addWidget(self.pushButton_quit)
        DeAnony.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DeAnony)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 26))
        self.menubar.setObjectName("menubar")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        DeAnony.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DeAnony)
        self.statusbar.setObjectName("statusbar")
        DeAnony.setStatusBar(self.statusbar)
        self.actionAdd_metadata = QtWidgets.QAction(DeAnony)
        self.actionAdd_metadata.setObjectName("actionAdd_metadata")
        self.menuTool.addAction(self.actionAdd_metadata)
        self.menuTool.addSeparator()
        self.menubar.addAction(self.menuTool.menuAction())

        self.retranslateUi(DeAnony)
        QtCore.QMetaObject.connectSlotsByName(DeAnony)

    def retranslateUi(self, DeAnony):
        _translate = QtCore.QCoreApplication.translate
        DeAnony.setWindowTitle(_translate("DeAnony", "MainWindow"))
        self.label_aux.setText(_translate("DeAnony", "Auxiliary Data"))
        self.Browse_aux.setText(_translate("DeAnony", "Browse"))
        self.label_anony.setText(_translate("DeAnony", "Anonymized Data"))
        self.Browse_anony.setText(_translate("DeAnony", "Browse"))
        self.pushButton_save.setText(_translate("DeAnony", "save the result"))
        self.label_result.setText(_translate("DeAnony", "Result"))
        self.pushButton_weight.setText(_translate("DeAnony", "get weight"))
        self.pushButton_run.setText(_translate("DeAnony", "run"))
        self.pushButton_totrun.setText(_translate("DeAnony", "weight + run"))
        self.pushButton_quit.setText(_translate("DeAnony", "Quit"))
        self.menuTool.setTitle(_translate("DeAnony", "Tool"))
        self.actionAdd_metadata.setText(_translate("DeAnony", "add metadata"))

